import { useCallback, useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import api from "../../services/api";
import "./Billing.css";

const asList = (data) => (Array.isArray(data) ? data : data.results || []);
const amount = (value) => Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const initialCharge = { description: "", item_type: "OTHER", quantity: 1, unit_price: "" };
const initialPayment = { amount: "", method: "CASH", reference: "", notes: "" };

export default function FolioDetail() {
  const { id } = useParams(); const navigate = useNavigate();
  const [folio, setFolio] = useState(null); const [items, setItems] = useState([]); const [payments, setPayments] = useState([]); const [references, setReferences] = useState({ reservations: [], guests: [], rooms: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [charge, setCharge] = useState(initialCharge); const [payment, setPayment] = useState(initialPayment); const [submitting, setSubmitting] = useState(null); const [formError, setFormError] = useState(null);

  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const [folioRes, itemRes, paymentRes, reservationRes, guestRes, roomRes] = await Promise.all([api.get(`/folios/${id}/`), api.get("/folio-items/"), api.get("/payments/"), api.get("/reservations/"), api.get("/guests/"), api.get("/rooms/")]);
      const currentFolio = folioRes.data;
      setFolio(currentFolio); setItems(asList(itemRes.data).filter((item) => String(item.folio) === String(id))); setPayments(asList(paymentRes.data).filter((item) => String(item.folio) === String(id))); setReferences({ reservations: asList(reservationRes.data), guests: asList(guestRes.data), rooms: asList(roomRes.data) });
    } catch (err) { setError(err.response?.data || err.message || "Failed to load folio."); } finally { setLoading(false); }
  }, [id]);

  useEffect(() => { Promise.resolve().then(load); }, [load]);
  const reservation = references.reservations.find((item) => String(item.id) === String(folio?.reservation)); const guest = references.guests.find((item) => String(item.id) === String(folio?.guest)); const room = references.rooms.find((item) => String(item.id) === String(reservation?.room));
  const serverError = (err, fallback) => err.response?.data || err.message || fallback;
  const submitCharge = async (event) => { event.preventDefault(); setFormError(null); if (!charge.description.trim() || Number(charge.quantity) < 1 || !Number.isFinite(Number(charge.unit_price))) { setFormError("Enter a description, a quantity of at least 1, and a valid unit price."); return; } setSubmitting("charge"); try { await api.post("/folio-items/", { folio: id, description: charge.description.trim(), item_type: charge.item_type, quantity: Number(charge.quantity), unit_price: charge.unit_price }); setCharge(initialCharge); await load(); } catch (err) { setFormError(serverError(err, "Could not add charge.")); } finally { setSubmitting(null); } };
  const submitPayment = async (event) => { event.preventDefault(); setFormError(null); const paymentAmount = Number(payment.amount); const balance = Number(folio?.balance); if (!Number.isFinite(paymentAmount) || paymentAmount <= 0) { setFormError("Payment amount must be greater than zero."); return; } if (paymentAmount > balance) { setFormError("Payment cannot exceed the current balance due."); return; } setSubmitting("payment"); try { await api.post("/payments/", { folio: id, amount: payment.amount, method: payment.method, reference: payment.reference, notes: payment.notes }); setPayment(initialPayment); await load(); } catch (err) { setFormError(serverError(err, "Could not record payment.")); } finally { setSubmitting(null); } };

  return <div className="billing-root"><div className="billing-header"><div><button className="btn-ghost small" onClick={() => navigate("/billing")}>Back to Billing</button><h1>Folio {folio ? `#${folio.id}` : ""}</h1></div><button className="btn-ghost small" disabled={loading || submitting !== null} onClick={load}>Refresh</button></div>
    {loading && <div className="billing-loading">Loading folio…</div>}{error && <div className="billing-error">{typeof error === "string" ? error : JSON.stringify(error)}</div>}
    {!loading && !error && folio && <><section className="folio-overview"><div><span>Guest</span><strong>{guest ? `${guest.first_name} ${guest.last_name}` : `Guest #${folio.guest}`}</strong></div><div><span>Reservation</span><strong>#{folio.reservation}</strong></div><div><span>Room</span><strong>{room?.room_number || "—"}</strong></div><div><span>Status</span><strong>{folio.status.replaceAll("_", " ")}</strong></div></section><section className="financial-summary"><div><span>Total charges</span><strong>{amount(folio.total_charges)}</strong></div><div><span>Total paid</span><strong>{amount(folio.total_paid)}</strong></div><div className="balance-summary"><span>Balance due</span><strong>{amount(folio.balance)}</strong></div></section>
      {formError && <div className="billing-error">{typeof formError === "string" ? formError : JSON.stringify(formError)}</div>}
      <div className="billing-forms"><form onSubmit={submitCharge}><h2>Add charge</h2><label>Description<input value={charge.description} disabled={submitting !== null} onChange={(event) => setCharge({ ...charge, description: event.target.value })} /></label><label>Type<select value={charge.item_type} disabled={submitting !== null} onChange={(event) => setCharge({ ...charge, item_type: event.target.value })}><option value="ROOM">Room</option><option value="SERVICE">Service</option><option value="FOOD">Food</option><option value="TAX">Tax</option><option value="DISCOUNT">Discount</option><option value="OTHER">Other</option></select></label><label>Quantity<input type="number" min="1" value={charge.quantity} disabled={submitting !== null} onChange={(event) => setCharge({ ...charge, quantity: event.target.value })} /></label><label>Unit price<input type="number" step="0.01" value={charge.unit_price} disabled={submitting !== null} onChange={(event) => setCharge({ ...charge, unit_price: event.target.value })} /></label><button className="btn" disabled={submitting !== null}>{submitting === "charge" ? "Adding…" : "Add charge"}</button></form>
      <form onSubmit={submitPayment}><h2>Record payment</h2><label>Amount<input type="number" min="0.01" step="0.01" value={payment.amount} disabled={submitting !== null || Number(folio.balance) <= 0} onChange={(event) => setPayment({ ...payment, amount: event.target.value })} /></label><label>Method<select value={payment.method} disabled={submitting !== null || Number(folio.balance) <= 0} onChange={(event) => setPayment({ ...payment, method: event.target.value })}><option value="CASH">Cash</option><option value="CARD">Card</option><option value="MPESA">M-Pesa</option><option value="TIGOPESA">Tigo Pesa</option><option value="AIRTEL_MONEY">Airtel Money</option><option value="BANK">Bank transfer</option></select></label><label>Reference<input value={payment.reference} disabled={submitting !== null || Number(folio.balance) <= 0} onChange={(event) => setPayment({ ...payment, reference: event.target.value })} /></label><label>Notes<textarea value={payment.notes} disabled={submitting !== null || Number(folio.balance) <= 0} onChange={(event) => setPayment({ ...payment, notes: event.target.value })} /></label><button className="btn" disabled={submitting !== null || Number(folio.balance) <= 0}>{submitting === "payment" ? "Recording…" : "Record payment"}</button></form></div>
      <section className="folio-ledger"><div><h2>Charges</h2>{items.length === 0 ? <p>No charges recorded.</p> : <table className="billing-table"><thead><tr><th>Description</th><th>Type</th><th>Quantity</th><th>Unit price</th><th>Total</th><th>Date</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.description}</td><td>{item.item_type}</td><td>{item.quantity}</td><td>{amount(item.unit_price)}</td><td>{amount(item.total)}</td><td>{item.created_at ? new Date(item.created_at).toLocaleString() : "—"}</td></tr>)}</tbody></table>}</div><div><h2>Payment history</h2>{payments.length === 0 ? <p>No payments recorded.</p> : <table className="billing-table"><thead><tr><th>Amount</th><th>Method</th><th>Reference</th><th>Status</th><th>Received by</th><th>Date</th></tr></thead><tbody>{payments.map((item) => <tr key={item.id}><td>{amount(item.amount)}</td><td>{item.method}</td><td>{item.reference || "—"}</td><td>{item.status}</td><td>{item.received_by || "—"}</td><td>{item.paid_at ? new Date(item.paid_at).toLocaleString() : "—"}</td></tr>)}</tbody></table>}</div></section></>}
  </div>;
}
