# Generated by Django 6.1 on 2026-08-13 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('hotels', '0001_initial'),
        ('reservations', '0002_reservation_actual_check_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='guests.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='hotels.hotel')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folio', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='FolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('ROOM', 'Room'), ('SERVICE', 'Service'), ('FOOD', 'Food'), ('TAX', 'Tax'), ('DISCOUNT', 'Discount'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.folio')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MPESA', 'M-Pesa'), ('TIGOPESA', 'Tigo Pesa'), ('AIRTEL_MONEY', 'Airtel Money'), ('BANK', 'Bank Transfer')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.folio')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
