import { useCallback, useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import api from "../../services/api";
import "./RoomTypes.css";

export default function RoomTypeDetail() {
  const { id } = useParams(); const navigate = useNavigate(); const [type, setType] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [mutating, setMutating] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await api.get(`/room-types/${id}/`); setType(response.data); } catch (err) { setError(err.response?.data || err.message || "Failed to load room type."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { Promise.resolve().then(load); }, [load]);
  const deactivate = async () => { setMutating("deactivate"); setError(null); try { await api.patch(`/room-types/${id}/`, { is_active: false }); await load(); } catch (err) { setError(err.response?.data || err.message || "Could not deactivate room type."); } finally { setMutating(null); } };
  const remove = async () => { if (!window.confirm("Delete this room type? This may fail if rooms still use it.")) return; setMutating("delete"); setError(null); try { await api.delete(`/room-types/${id}/`); navigate("/room-types"); } catch (err) { setError(err.response?.data || err.message || "Could not delete room type."); } finally { setMutating(null); } };
  return <div className="room-types-root"><div className="room-types-header"><div><button className="btn-ghost small" onClick={() => navigate("/room-types")}>Back to Room Types</button><h1>{type?.name || "Room Type"}</h1></div>{type && <div className="room-types-actions"><button className="btn-ghost small" disabled={mutating !== null} onClick={() => navigate(`/room-types/${id}/edit`)}>Edit</button>{type.is_active && <button className="btn-ghost small" disabled={mutating !== null} onClick={deactivate}>{mutating === "deactivate" ? "Deactivating…" : "Deactivate"}</button>}<button className="btn-ghost small" disabled={mutating !== null} onClick={remove}>{mutating === "delete" ? "Deleting…" : "Delete"}</button></div>}</div>{loading && <div className="room-types-loading">Loading room type…</div>}{error && <div className="room-types-error">{typeof error === "string" ? error : JSON.stringify(error)}</div>}{!loading && !error && type && <div className="room-type-detail"><div><span>Description</span><strong>{type.description || "—"}</strong></div><div><span>Maximum occupancy</span><strong>{type.max_occupancy}</strong></div><div><span>Base price</span><strong>{Number(type.base_price).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</strong></div><div><span>Status</span><strong>{type.is_active ? "Active" : "Inactive"}</strong></div><div><span>Created</span><strong>{type.created_at ? new Date(type.created_at).toLocaleString() : "—"}</strong></div><div><span>Updated</span><strong>{type.updated_at ? new Date(type.updated_at).toLocaleString() : "—"}</strong></div></div>}</div>;
}
